# Generated by Django 3.2.6 on 2022-06-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('dial', models.CharField(max_length=5, verbose_name='Canal')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radio.city')),
            ],
            options={
                'verbose_name': 'Rádio',
                'verbose_name_plural': 'Rádios',
            },
        ),
    ]
